# Add application configuration variables here, as shown below.
YELP_CONSUMER_KEY: CDRnqVgqToQADjpdv4cPUA
YELP_CONSUMER_SECRET: wW5meo7KiFELtUpEvYQuyYB3dzA
YELP_TOKEN: 4bcpfqs7cKIoKu5RrsbWFeeLK1FXhcgr 
YELP_TOKEN_SECRET: gQ8Wi0RJerudN_bNZzMjle6KUhA